syntax = "proto3";

message DevConfigFetchResDTO {
  uint32 time = 1;
  int64 tid = 2;
  string dtu_sn = 3;
  string dev_sn = 4;
  int32 package_now = 5;
  int32 rule_type = 6;
}

message DevConfigFetchReqDTO {
  uint32 time = 1;
  int64 tid = 2;
  int32 rule_id = 3;
  string data = 4;
  int32 crc = 5;
  string dtu_sn = 6;
  string dev_sn = 7;
  int32 package_nub = 10;
  int32 package_now = 11;
  int32 rule_type = 12;
}

message DevConfigPutResDTO {
  uint32 time = 1;
  int64 tid = 2;
  int32 rule_id = 3;
  string data = 4;
  int32 crc = 5;
  string dtu_sn = 6;
  string dev_sn = 7;
  int32 package_nub = 10;
  int32 package_now = 11;
  repeated int64 mi_to_sn = 12;
  int32 rule_type = 13;
}

message DevConfigPutReqDTO {
  uint32 time = 1;
  int64 tid = 2;
  string dtu_sn = 3;
  string dev_sn = 4;
  int32 status = 5;
  int32 package_now = 6;
  repeated int64 mi_to_sn = 7;
  int32 rule_type = 8;
  int32 err_code = 9;
}

message DevConfigReportReqDTO {
  uint32 time = 1;
  int64 tid = 2;
  int32 rule_id = 3;
  string data = 4;
  int32 crc = 5;
  string dtu_sn = 6;
  string dev_sn = 7;
  int32 package_nub = 10;
  int32 package_now = 11;
  int32 rule_type = 12;
}

message DevConfigReportResDTO {
  uint32 time = 1;
  int64 tid = 2;
  string dtu_sn = 3;
  string dev_sn = 4;
  int32 package_now = 5;
  int32 rule_type = 6;
}
